name: Setup

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 6
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'pnpm'
    - run: pnpm install
      shell: bash
