version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:16

commands:
  setup-dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: install-packages
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  test:
    steps:
      - run:
          name: unit test by jest
          command: yarn test
  lint:
    steps:
      - run:
          name: eslint, stylelint and type check
          command: yarn lint
  persist-build:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - dist
  attach-build:
    steps:
      - attach_workspace:
          root: .
          paths:
            - dist
  build-dev:
    steps:
      - run:
          name: build for development
          command: yarn build:dev
  build-stg:
    steps:
      - run:
          name: build for staging
          command: yarn build:stg
  build-prod:
    steps:
      - run:
          name: build for production
          command: yarn build:prod

jobs:
  test-job:
    executor:
      name: node
    steps:
      - checkout
      - setup-dependencies
      - lint
      - test
  build-dev-job:
    executor:
      name: node
    steps:
      - checkout
      - setup-dependencies
      - build-dev
      - persist-build
  build-stg-job:
    executor:
      name: node
    steps:
      - checkout
      - setup-dependencies
      - build-stg
      - persist-build
  build-prod-job:
    executor:
      name: node
    steps:
      - checkout
      - setup-dependencies
      - build-prod
      - persist-build

workflows:
  test-and-build:
    jobs:
      - test-job
      - build-prod-job:
          filters:
            branches:
              only:
                - master
          requires:
            - test-job
      - build-dev-job:
          filters:
            branches:
              ignore:
                - master
          requires:
            - test-job
      - build-stg-job:
          filters:
            branches:
              ignore:
                - master
          requires:
            - test-job
