name: Check

on:
  pull_request:
    branch: ['*', '!main']
jobs:
  check:
    runs-on: ubuntu-latest
    name: lint and compile
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Run lint
        run: |
          pnpm lint
          pnpm format

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run test
        run: pnpm test

      - name: Run compile
        run: pnpm build
